[workspace]
members = [
    "lazyext",
    "lazyext-bytes",
    "lazyext-fs",
    "lazyext-macros",
    "lazyext-sync"
]

[profile.bench]
opt-level = 3
debug = false
codegen-units = 1
lto = 'thin'
incremental = false
debug-assertions = false
overflow-checks = false
rpath = false